// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSection(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSection'](arg1, arg2, arg3);
}

export function CreatePage(arg1) {
  return window['go']['main']['App']['CreatePage'](arg1);
}

export function DeletePage(arg1) {
  return window['go']['main']['App']['DeletePage'](arg1);
}

export function DeleteSection(arg1, arg2) {
  return window['go']['main']['App']['DeleteSection'](arg1, arg2);
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function ListPages() {
  return window['go']['main']['App']['ListPages']();
}

export function ListSections(arg1) {
  return window['go']['main']['App']['ListSections'](arg1);
}

export function PublishAll() {
  return window['go']['main']['App']['PublishAll']();
}

export function SaveSite(arg1) {
  return window['go']['main']['App']['SaveSite'](arg1);
}

export function SetArticle(arg1, arg2) {
  return window['go']['main']['App']['SetArticle'](arg1, arg2);
}

export function SetAside(arg1, arg2) {
  return window['go']['main']['App']['SetAside'](arg1, arg2);
}

export function SetCSS(arg1, arg2) {
  return window['go']['main']['App']['SetCSS'](arg1, arg2);
}

export function SetContact(arg1, arg2) {
  return window['go']['main']['App']['SetContact'](arg1, arg2);
}

export function SetCopyright(arg1, arg2) {
  return window['go']['main']['App']['SetCopyright'](arg1, arg2);
}

export function SetFooter(arg1, arg2) {
  return window['go']['main']['App']['SetFooter'](arg1, arg2);
}

export function SetLogo(arg1, arg2) {
  return window['go']['main']['App']['SetLogo'](arg1, arg2);
}

export function SetMain(arg1, arg2) {
  return window['go']['main']['App']['SetMain'](arg1, arg2);
}

export function SetMeta(arg1, arg2) {
  return window['go']['main']['App']['SetMeta'](arg1, arg2);
}

export function SetNav(arg1, arg2) {
  return window['go']['main']['App']['SetNav'](arg1, arg2);
}

export function SetScripts(arg1, arg2) {
  return window['go']['main']['App']['SetScripts'](arg1, arg2);
}

export function SetSocial(arg1, arg2) {
  return window['go']['main']['App']['SetSocial'](arg1, arg2);
}

export function UpdateSection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSection'](arg1, arg2, arg3, arg4);
}

export function UploadImage(arg1, arg2) {
  return window['go']['main']['App']['UploadImage'](arg1, arg2);
}
