// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSection(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSection'](arg1, arg2, arg3);
}

export function CreatePage(arg1) {
  return window['go']['main']['App']['CreatePage'](arg1);
}

export function DeletePage(arg1) {
  return window['go']['main']['App']['DeletePage'](arg1);
}

export function DeleteSection(arg1, arg2) {
  return window['go']['main']['App']['DeleteSection'](arg1, arg2);
}

export function ListPages() {
  return window['go']['main']['App']['ListPages']();
}

export function ListSections(arg1) {
  return window['go']['main']['App']['ListSections'](arg1);
}

export function PublishSite() {
  return window['go']['main']['App']['PublishSite']();
}

export function UpdateSection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSection'](arg1, arg2, arg3, arg4);
}
