// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddSection(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreatePage(arg1:string):Promise<string>;

export function DeletePage(arg1:string):Promise<boolean>;

export function DeleteSection(arg1:string,arg2:string):Promise<boolean>;

export function ListPages():Promise<Array<main.Page>>;

export function ListSections(arg1:string):Promise<Array<main.Section>>;

export function PublishSite():Promise<string>;

export function UpdateSection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;
